version: '3'

services:
  pap:
    build:
      context: .
      dockerfile: ./pap/Dockerfile
      args:
        url: https://github.com/kaser137/test.git
        branch: master
    environment:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

    volumes:
    - /home/alexander/projects/test/ddd:/alex/test/

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
#    command: ls -al ./venv/bin
    environment:
      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    depends_on:
      - pap
    volumes:
      - /home/alexander/projects/test/ddd:/alex/test/
#volumes:
#  ddd:

