version: '3'

services:
  pap:
    build:
      context: .
      dockerfile: app/Dockerfile.last
      args:
        url: https://github.com/kaser137/test.git
        branch: master
        path: test
#    environment:
#      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1

    volumes:
    - ddd:/alex/test/

  app:
    build:
      context: .
      dockerfile: ./Dockerfileapp
#    command: sleep 720
#    environment:
#      GIT_DISCOVERY_ACROSS_FILESYSTEM: 1
    depends_on:
      - pap

    volumes:

      - ddd:/alex/test/

volumes:
  ddd:

